# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tasks < Formula
  desc "A simple CLI for task management"
  homepage "https://github.com/PriyabrataMo/tasks"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PriyabrataMo/tasks/releases/download/v0.2.1/tasks_0.2.1_darwin_amd64.tar.gz"
      sha256 "40a342bb5bba6a666c02ce41f0f0d8458dd3cdc9f4d6894d04e1a46083e12845"

      def install
        bin.install "tasks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PriyabrataMo/tasks/releases/download/v0.2.1/tasks_0.2.1_darwin_arm64.tar.gz"
      sha256 "e7d239be3a8596b058bb2c6060f842c4fe114f5ef892ef02ea1c64edd368a58e"

      def install
        bin.install "tasks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PriyabrataMo/tasks/releases/download/v0.2.1/tasks_0.2.1_linux_amd64.tar.gz"
        sha256 "5c6d95362a9059cd4d45da20725bb9264054d01ba4da6a3681d87cd0db5ec89c"

        def install
          bin.install "tasks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PriyabrataMo/tasks/releases/download/v0.2.1/tasks_0.2.1_linux_arm64.tar.gz"
        sha256 "de2528c083b5ea8a6a9c42c30de99b202df233fa403df0b3be1efa2c4768d9ae"

        def install
          bin.install "tasks"
        end
      end
    end
  end
end
